name: Refresh repository indexes & snapshots

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET (if indexers exist)
        if: ${{ hashFiles('Tools/**/*.csproj') != '' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run repository indexers (best-effort)
        shell: bash
        run: |
          set -e
          # If your repo has scripts or projects that generate indexes/snapshots, run them conditionally.
          if [ -f Tools/Build/generate-index.sh ]; then
            bash Tools/Build/generate-index.sh || true
          fi
          if [ -f Tools/DocsIndex/DocsIndex.csproj ]; then
            dotnet run --project Tools/DocsIndex/DocsIndex.csproj || true
          fi
          if [ -f Tools/Indexing/Indexing.csproj ]; then
            dotnet run --project Tools/Indexing/Indexing.csproj || true
          fi

      - name: Stage & commit index/snapshot files if changed (robust)
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Explicit, safe staging of the known outputs. Missing paths are ignored.
          git add INDEX.md Docs/INDEX.md CODE_INDEX.md CODE_SNAPSHOT.txt SYMBOLS.json XML_INDEX.md XML_SNAPSHOT.txt 2>/dev/null || true
          # Keep XML samples/schemas where your live links point.
          git add Docs/Templates/Defs/ 2>/dev/null || true

          # Commit only if something is staged
          if ! git diff --cached --quiet --exit-code; then
            git commit -m "ci: refresh repository index & XML samples"
            git push
          else
            echo "No index changes"
          fi
